### ISSUE TITLE
Название пакета restapi в go.mod не даёт спарсить репу

### ISSUE THREAD

**Issue by ubahwin** [shuryak/api-wrappers#1]
Мой `go.mod`:

`require github.com/shuryak/api-wrappers latest`

При попытке *go get* вашего репозитория появляется ошибка:

```
# get https://proxy.golang.org/github.com/shuryak/api-wrappers/@latest: 200 OK (0.011s)
go: github.com/shuryak/api-wrappers@v0.0.0-20240430150751-8dbc32b3dc36: parsing go.mod:
	module declares its path as: restapi
	        but was required as: github.com/shuryak/api-wrappers
```

Ваш `go.mod`:

```
module restapi

go 1.22
```

[Тут похожая проблема](https://github.com/google/gnostic/issues/262) и люди предлагают откатиться до версии, где название ещё не меняли

**Comment by shuryak** [comment]
Fixed in b72e68d
